### ISSUE TITLE
How to run it

### ISSUE THREAD

**Issue by prabaprakash** [nandhanandy92/SSO_POC-IdentityServer4-JWT#1]
Please add it in readme

**Comment by nandhanandy92** [comment]
@prabaprakash I'm planning for a detailed read-me but for a quick tip on how to run it

Since it's asp.net core 3.0 project you need latest stable version of vs 2019

or you can run it using VS code on any machine with the respective run-time installed.

1. download and install dotnet core 3.0 sdk .
2. clone this repo.
3. in the src folder you can see 3 projects a simple api endpoint and a simple identity server and a simple console application which hits the api by getting a token from Identity server first.
4. cd into each project and run using dotnet run command in this order i)Identity server ii)API and the iii) client.
